### ISSUE TITLE
Rename the plugin / repository

### ISSUE THREAD

**Issue by chrisranderson** [chrisranderson/beholder#43]
Wizards of the Coast might not be happy with the name "beholder". From their [System Reference Document (pdf)](http://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf):

> The following items are designated Product Identity, as defined in Section 1(e) of the Open Game License Version 1.0a, and are subject to the conditions set forth in Section 7 of the OGL, and are not Open Content: Dungeons & Dragons, D&D, Player’s Handbook .... **beholder**, gauth, carrion crawler, tanar’ri, baatezu, displacer beast, githyanki, githzerai, mind flayer, illithid, umber hulk, yuan-ti.

Suggestions welcome!

**Comment by chrisranderson** [comment]
Potential options:
- tfvideo (Also IP issues? May have to ask about this) or some variation: tf_video, tf-video. Maybe tbvideo?
  - I like the practicality of this idea.
- lens
- viewfinder
- Viddy McVidface or Tensy McTensorface, etc.
- defer responsibility to the TensorBoard folks if it gets merged :)

**Comment by chrisranderson** [comment]
@jart @wchargin this totally isn't your job, but can I get some advice on this as a favor? I'd like to post this on Reddit or something, but I don't want to have rename it after I put it out in the wild.

I'm leaning toward something like tensorboard-video or tensorflow-video (maybe without a dash or with an underscore) but I was thinking that Google might not appreciate that. Do you have any suggestions? Maybe something that gets across the point that it is a live visualization?

**Comment by jart** [comment]
I would advise holding off on going public until we collect feedback. I've started doing that today. Once that's done, we can work on rhetoric. The last media piece I did was [Operation Rosehub](https://opensource.googleblog.com/2017/03/operation-rosehub.html) which got picked up by [Hacker News](https://news.ycombinator.com/item?id=13769727), [TrendinTech](http://trendintech.com/2017/03/11/google-employees-to-the-rescue-with-operation-rosehub/), [BleepingComputer](https://www.bleepingcomputer.com/news/security/50-google-engineers-volunteered-to-patch-thousands-of-java-open-source-projects/), [Naked Security](https://nakedsecurity.sophos.com/2017/03/07/google-leads-guerilla-patching-of-big-vulnerability-in-open-source-projects/), etc. I am happy to help, and do consider it my job, because I see your success as benefiting the TensorBoard project.

**Comment by chrisranderson** [comment]
Okay, that sounds like good advice. I'll wait. :) Thank you for getting feedback!

**Comment by jart** [comment]
I think the name Beholder is fine. There are actually two live registered trademarks, but they don't apply to what you're doing.

- [Trademark 87177865](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:him5vu.2.2) applies to computer and board games
- [Trademark 86808670](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:him5vu.2.8) applies to camera accessories

**Comment by chrisranderson** [comment]
Okay, I'll close this until I get served or something.

**Comment by jart** [comment]
I'm in process of talking with people on our end to make sure you're doing everything by the book. I don't think there's any reason to be concerned. I'll let you know if I learn that there's more you can be doing. Also, if anyone reaches out to you with trademark concerns, feel free to contact us, since people on our end would probably be interested in helping.
